apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-docksmith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-docksmith
  template:
    metadata:
      labels:
        app: react-docksmith
    spec:
      containers:
        - name: react-docksmith
          image: adeleke1/react-docksmith:v1.1.0
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: react-docksmith-service
spec:
  type: NodePort
  selector:
    app: react-docksmith
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32313
